### PR TITLE
add build/packaging tools and script.

### LINKED ISSUE #11: Build script producing an executable electron app
(How do we make an executable app from the repo?)

### PR DESCRIPTION
**Pull request by tafsiri**
This builds app packages for the various platforms. Closes #11 

Note i have only tested the os x app that comes as part of the output of this.

ping @kanitw @vlandham

### CODE REVIEW

**Comment by kanitw** [comment]
The code looks good to me.  @vlandham  if you're testing this anyway, feel free to merge.  

(Ping me if you want me to test :p)

**Comment by kanitw** [comment]
It still needs rebasing though :)

**Review by kanitw — APPROVED** [review]

**Comment by tafsiri** [comment]
@kanitw ok rebased and ready.

**Comment by vlandham** [comment]
i'll merge it!

**Pull request merged**
